nelmio_api_doc:
    documentation:
        info:
            title: OpenClassrooms P7 BileMo API
            description: This is REST API BileMo OpenClassrooms Développeur d'Application PHP/Symfony !
            version: 2.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: GETS THE JWT TOKEN  FOR AUTHENTICATION.
                    requestBody:
                        description: Create a new JWT Token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
            /api/users:
                post:
                    operationId: postUserItem
                    summary: Posts new user's data.
                    requestBody:
                        description: Create a new user
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/UserData'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@apiclientone.com
                        password:
                            type: string
                            default: adminpassword
                UserData:
                    type: object
                    properties:
                        email:
                            type: string
                            default: user@userapi.com
                        lastname:
                            type: string
                            default: yourlastname
                        firstname:
                            type: string
                            default: yourfirstname
                        comment:
                            type: string
                            default: your comment
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc